### PR TITLE
Fix "Koren Kii Error" links

### PR DESCRIPTION
**Pull request by hyperupcall**
**Description**

When browsing this wonderful site, I noticed that these links were out of date. Didn't notice a `CONTRIBUTING.md` or similar so not exactly sure how project is built (with Crowdin and all, and not many PRs since #117 landed), so I just did a recursive-directory find & replace of the slug. Things linked properly when running `npm run docs:dev` (in addition to `docs:build` and `docs:preview`). If you prefer a different format / things done differently, I'd be happy to fix things up in accordance

### CODE REVIEW

**Comment by playerjmr** [comment]
TBH the title itself seems confusing too as "Korean Kii" is the name of the homebrew application for removing the "Korean Key" which causes the error 003 brick in the first place. I think I ought to just change the header altogether

**Comment by playerjmr** [comment]
also, please dont make commits to other translations, as that will cause conflicts with crowdin.

**Comment by hyperupcall** [comment]
@playerjmr Agreed, if that is the case, then "Korean Key" may not be the best title. I've updated the PR to only change the base markdown files, feel free to merge or close depending on if the title is acceptable

**Comment by playerjmr** [comment]
Yeah this is fine for now, The header change is a whole different project I dont want to deal with rn especially since im starting a new job tomorrow.

**Pull request merged**
