### PR TITLE
Update WiiConnect24 page

### PR DESCRIPTION
**Pull request by Naim2000**
Though this page may as well be migrated to rc24.xyz

### CODE REVIEW

**Comment by DardelHMB** [comment]
Why not discontinue the rc24 guide on the page and use wiilinks guide? given that they use the same patcher now

**Comment by lifehackerhansol** [comment]
> Though this page may as well be migrated to rc24.xyz

I have to agree. We shouldn't have to maintain installation instructions for this.

**Comment by Naim2000** [comment]
Would probably delete the page right now but that is probably going to clash with the redirects pr

**Comment by lifehackerhansol** [comment]
Just do it, I can fix PR later

**Pull request merged**
