### PR TITLE
Update nintendont.md

### PR DESCRIPTION
**Pull request by playerjmr**
fixed the IPL description + made the file structure look nicer

**Description**

### CODE REVIEW

**Comment by SCOTT0852** [comment]
I think the paths should be changed to those present on [the wiki version of the page](https://wiki.hacks.guide/wiki/Wii:Nintendont). There's no need to put single-disc games into subfolders. Really, the whole page should be updated to reflect the wiki's changes, but the game paths are most relevant here.

**Comment by lifehackerhansol** [comment]
Can confirm it renders fine at the very least.

**Comment by playerjmr** [comment]
> I think the paths should be changed to those present on [the wiki version of the page](https://wiki.hacks.guide/wiki/Wii:Nintendont). There's no need to put single-disc games into subfolders. Really, the whole page should be updated to reflect the wiki's changes, but the game paths are most relevant here.

That’s literally how Nintendont reads games. All games have to be in sub folders whether you want them to be there or not.

**Comment by SCOTT0852** [comment]
> All games have to be in sub folders whether you want them to be there or not.
I literally have my setup so that no games are in subfolders and it works fine. I'm speaking from experience. It's undocumented, but it works.

**Comment by playerjmr** [comment]
> > All games have to be in sub folders whether you want them to be there or not.
> 
> I literally have my setup so that no games are in subfolders and it works fine. I'm speaking from experience. It's undocumented, but it works.

if you want gamecube games to read and play in usbloader gx this exact file structure is required even if nintendont by itself is less strict.

**Pull request merged**
