### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by ihaveamac**

### CODE REVIEW

**Comment by LNLenost** [comment]
Why wasn't this merged?

There are some new translations

**Comment by lilyuwuu** [comment]
merges aren't automatic, they happen whenever someone remembers to (or if there were a lot of significant changes such that the translations are communicating outdated information)

**Comment by LNLenost** [comment]
Ohh ok

**Comment by LNLenost** [comment]
I thought PR from the account which has access to the Crowdin were merged
automatically

**Pull request merged**
