### PR TITLE
Update home.md to share wii.guide redirect info

### PR DESCRIPTION
**Pull request by mpgiii**
Add information about wii.guide now redirecting to this page

**Description**

This pull request is simply to add a notice to the home page of wii.hacks.guide to inform users of our site now being the home of the Wii hacking guide, as well as to mention that WiiLink and RiiConnect24 are merging.

More work will be needed to update our WiiConnect24 and RiiConnect24 pages.

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
As mentioned on GitHub, I disagree with this change. It doesn't really provide any benefit.

I'm open to opinions from other guide maintainers however.

**Comment by grunt22fox** [comment]
This may be of some use to us due to the fact that wii.guide is still the top result on Google, and that we have to wait for SEO optimization with the hacks.guide domain. Specifically, there are going to be pages that simply link to 404s that we removed or renamed, so I think it would be wise to have *some kind of notice* maybe not on the front page, but as an explanation for why a page might be a dead link? Also begs the question of whether or not we would want to set up redirects for certain pages that did exist on wii.guide but whose content was moved on hacks.guide

**Comment by lifehackerhansol** [comment]
I would really rather we don't have redirects. GitHub Pages doesn't support that mess of a thing

We can at the very least add a "this page was removed. See why here" I guess, but we should do that in another commit

So, if not the front page... faq?
I guess we can add a small alert that "the wii.guide has been moved to wii.hacks.guide. see why here" or sumn

**Comment by grunt22fox** [comment]
With the new 410 redirects, and the fact that this has sat here for 3 weeks without any developments, I'm going to go ahead and close it until further notice.

**Pull request closed without merging**
